
$CLASS_DECLERATION_READER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\CLASS.DECLERATION.READER"

$DESCRIPTOR_FILE_READER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\DESCRIPTOR.FILE.READER"

$DESCRIPTOR_FILE_WRITER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\DESCRIPTOR.FILE.WRITER"

$CLIENT_CLASS_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\CLIENT.CLASS.BUILDER"

$EXECUTABLE_FILE_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\EXECUTABLE.FILE.BUILDER"

$SMART_POINTER_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\SMART.POINTER.BUILDER"

$SERVER_CLASS_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\SERVER.CLASS.BUILDER"

$KERNEL_DEVELOPMENT_PATH="D:\PCYNLITX.PROJECT.WINDOWS\KERNEL.DEVELOPMENT"

$GUI_DEVELOPMENT_PATH="D:\PCYNLITX.PROJECT.WINDOWS\GUI.DEVELOPMENT"


cd $CLASS_DECLERATION_READER_PATH\Tools

PowerShell .\Build.Make.Files.ps1


cd $CLASS_DECLERATION_READER_PATH\ProcessInitialization

PowerShell .\Build.Make.Files.ps1


cd $CLASS_DECLERATION_READER_PATH\DataBaseManagement

PowerShell .\Build.Make.Files.ps1


cd $CLASS_DECLERATION_READER_PATH\ClassReader

PowerShell .\Build.Make.Files.ps1


cd $DESCRIPTOR_FILE_READER_PATH

PowerShell .\Build.Make.Files.ps1


cd $DESCRIPTOR_FILE_WRITER_PATH

PowerShell .\Build.Make.Files.ps1


cd $CLIENT_CLASS_BUILDER_PATH

PowerShell .\Build.Make.Files.ps1


cd $EXECUTABLE_FILE_BUILDER_PATH

PowerShell .\Build.Make.Files.ps1


cd $SMART_POINTER_BUILDER_PATH

PowerShell .\Build.Make.Files.ps1


cd $SERVER_CLASS_BUILDER_PATH

PowerShell .\Build.Make.Files.ps1


cd $KERNEL_DEVELOPMENT_PATH

PowerShell .\Build.Make.Files.ps1


cd $GUI_DEVELOPMENT_PATH

PowerShell .\Build.Make.Files.ps1
