
$CLASS_DECLERATION_READER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\CLASS.DECLERATION.READER"

$DESCRIPTOR_FILE_READER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\DESCRIPTOR.FILE.READER"

$DESCRIPTOR_FILE_WRITER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\DESCRIPTOR.FILE.WRITER"

$CLIENT_CLASS_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\CLIENT.CLASS.BUILDER"

$EXECUTABLE_FILE_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\EXECUTABLE.FILE.BUILDER"

$SMART_POINTER_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\SMART.POINTER.BUILDER"

$SERVER_CLASS_BUILDER_PATH="D:\PCYNLITX.PROJECT.WINDOWS\SERVER.CLASS.BUILDER"

$KERNEL_DEVELOPMENT_PATH="D:\PCYNLITX.PROJECT.WINDOWS\KERNEL.DEVELOPMENT"

$GUI_DEVELOPMENT_PATH="D:\PCYNLITX.PROJECT.WINDOWS\GUI.DEVELOPMENT"

cd $CLASS_DECLERATION_READER_PATH

PowerShell .\Compile.CDR.ps1

cd $DESCRIPTOR_FILE_READER_PATH

PowerShell .\Compile_Descriptor_File_Reader_Project.ps1

cd $DESCRIPTOR_FILE_WRITER_PATH

PowerShell .\Compile_Descriptor_File_Writer_Project.ps1

cd $CLIENT_CLASS_BUILDER_PATH

PowerShell .\Compile_Client_Class_Builder_Project.ps1

cd $EXECUTABLE_FILE_BUILDER_PATH

PowerShell .\Compile_Executable_File_Builder_Project.ps1

cd $SMART_POINTER_BUILDER_PATH

PowerShell .\Compile.MT.SmartPointer.ps1

cd $SERVER_CLASS_BUILDER_PATH

PowerShell .\Compile_Server_Class_Builder_Project.ps1

cd $KERNEL_DEVELOPMENT_PATH

PowerShell .\Compile_Kernel_Development_Project.ps1

cd $GUI_DEVELOPMENT_PATH

PowerShell .\GUI_Compiler.ps1

PowerShell .\Update_Icon_Files.ps1

Library_Updater.exe
