
BASE_DIRECTORY=~/PARSEC_STREAMCLUSTER_STD_THREAD
PCYNLITX_PROJECT_HEADERS=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.HEADER.FILES
PCYNLITX_LIBRARY_DIRECTORY=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.LIBRARY

g++ -I$BASE_DIRECTORY -I$PCYNLITX_PROJECT_HEADERS \
    -L$BASE_DIRECTORY -L$PCYNLITX_LIBRARY_DIRECTORY -o parsec_streamcluster_std_thread \
     parsec_streamcluster_std_thread.cpp -include thread_argument.h \
    -include $PCYNLITX_PROJECT_HEADERS/Cpp_FileOperations.h \
    -include $PCYNLITX_PROJECT_HEADERS/IntToCharTranslater.h \
    -lpthread -lmptools
