
BASE_DIRECTORY=~/MULTITHREADED_NUMBER_COUNTER_PCYNLITX
PROJECT_HEADERS=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.HEADER.FILES
PROJECT_LIBRARY=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.LIBRARY

g++ -I$BASE_DIRECTORY -I$PROJECT_HEADERS \
    -L$BASE_DIRECTORY -L$PROJECT_LIBRARY \
    -o File_Cropper File_Cropper.cpp -include Cpp_FileOperations.h -lmptools
