

PROJECT_HEADER_FILES=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.HEADER.FILES
PROJECT_LIBRARY_DIRECTORY=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.LIBRARY

g++ -std=c++14 -I$PROJECT_HEADER_FILES -L$PROJECT_LIBRARY_DIRECTORY \
    -o Rodinia_Kmeans_Pcynlitx_Test Rodinia_Kmeans_Pcynlitx_Test.cpp \
    -include Cpp_FileOperations.h -lmptools
