


# This files updates fedora package files

FEDORA_PROJECT_DIRECTORY=~/PCYNLITX.PROJECT/PACKAGE.BUILD.TOOLS/Fedora_Packaging
FEDORA_RELEASE=~/PCYNLITX.PROJECT.LIBRARY/PCYNLITX_RELEASE_PACKAGES/FEDORA_RELEASE/pcynlitx_fedora
FEDORA_USER_DIR=$FEDORA_RELEASE/usr
FEDORA_USER_BIN=$FEDORA_USER_DIR/bin
FEDORA_USER_SHARE=$FEDORA_USER_DIR/share
FEDORA_USER_SHARE_DOC=$FEDORA_USER_SHARE/doc
FEDORA_USER_SHARE_PCYNLITX=$FEDORA_USER_SHARE/Pcynlitx
FEDORA_USER_SHARE_PCYNLITX_APP=$FEDORA_USER_SHARE/applications
FEDORA_USER_SHARE_PCYNLITX_ICONS=$FEDORA_USER_SHARE_PCYNLITX/icons


cd $FEDORA_PROJECT_DIRECTORY/usr/share/doc

cp Copyright $FEDORA_USER_SHARE_DOC


cd $FEDORA_PROJECT_DIRECTORY/usr/share/applications

cp pcynlitx.desktop $FEDORA_USER_SHARE_PCYNLITX_APP



cd $FEDORA_PROJECT_DIRECTORY/usr/share/Pcynlitx/icons

cp archive.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp build_executable.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp close_tab.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp close.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp empty_project_file.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp file_save.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp file.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp folder.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp help_documents.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp open_terminal.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp open_tree_view.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp pane_close_icon.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp pcynlitx.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp print_descriptions.png $FEDORA_USER_SHARE_PCYNLITX_ICONS

cp select_project_file.png $FEDORA_USER_SHARE_PCYNLITX_ICONS


cd $FEDORA_PROJECT_DIRECTORY/usr/share/Pcynlitx/

cp Intro_File.png $FEDORA_USER_SHARE_PCYNLITX

cd $FEDORA_USER_BIN

sudo chmod 0777 Description_Printer

sudo chmod 0777 Description_Recorder

sudo chmod 0777 Descriptor_File_Reader

sudo chmod 0777 Empty_Process_Descriptor_File_Builder

sudo chmod 0777 Pcynlitx_Kernel

sudo chmod 0777 Pcynlitx

sudo chmod 0777 MT_Project_Builder
