

# This files updates debian package files

UBUNTU_PROJECT_DIRECTORY=~/PCYNLITX.PROJECT/PACKAGE.BUILD.TOOLS/Ubuntu_Packaging
UBUNTU_RELEASE=~/PCYNLITX.PROJECT.LIBRARY/PCYNLITX_RELEASE_PACKAGES/UBUNTU_RELEASE/pcynlitx_ubuntu
UBUNTU_CONTROL_DIR=$UBUNTU_RELEASE/DEBIAN
UBUNTU_USER_DIR=$UBUNTU_RELEASE/usr
UBUNTU_USER_BIN=$UBUNTU_USER_DIR/bin
UBUNTU_USER_SHARE=$UBUNTU_USER_DIR/share
UBUNTU_USER_SHARE_DOC=$UBUNTU_USER_SHARE/doc
UBUNTU_USER_SHARE_PCYNLITX=$UBUNTU_USER_SHARE/Pcynlitx
UBUNTU_USER_SHARE_PCYNLITX_APP=$UBUNTU_USER_SHARE_PCYNLITX/applications
UBUNTU_USER_SHARE_PCYNLITX_ICONS=$UBUNTU_USER_SHARE_PCYNLITX/icons
GUI_DEVELOPMENT=~/PCYNLITX.PROJECT/GUI.DEVELOPMENT



cd $GUI_DEVELOPMENT

bash Update_Project_Binaries.sh > Compiler_Output

bash GUI_Compiler.sh > Compiler_Output

cd $UBUNTU_PROJECT_DIRECTORY/DEBIAN

cp control $UBUNTU_CONTROL_DIR

cp postinst $UBUNTU_CONTROL_DIR

cp postrm $UBUNTU_CONTROL_DIR

cp preinst $UBUNTU_CONTROL_DIR



cd $UBUNTU_PROJECT_DIRECTORY/usr/share/doc

cp Copyright $UBUNTU_USER_SHARE_DOC


cd $UBUNTU_PROJECT_DIRECTORY/usr/share/Pcynlitx/applications

cp pcynlitx.desktop $UBUNTU_USER_SHARE_PCYNLITX_APP



cd $UBUNTU_PROJECT_DIRECTORY/usr/share/Pcynlitx/icons

cp archive.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp build_executable.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp close_tab.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp close.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp empty_project_file.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp file_save.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp file.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp folder.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp help_documents.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp open_terminal.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp open_tree_view.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp pane_close_icon.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp pcynlitx.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp print_descriptions.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS

cp select_project_file.png $UBUNTU_USER_SHARE_PCYNLITX_ICONS


cd $UBUNTU_PROJECT_DIRECTORY/usr/share/Pcynlitx/

cp Intro_File.png $UBUNTU_USER_SHARE_PCYNLITX

cd $UBUNTU_USER_BIN

sudo chmod 0777 Description_Printer

sudo chmod 0777 Description_Recorder

sudo chmod 0777 Descriptor_File_Reader

sudo chmod 0777 Empty_Process_Descriptor_File_Builder

sudo chmod 0777 Pcynlitx_Kernel

sudo chmod 0777 MT_Project_Builder

sudo chmod 0777 Pcynlitx
