#!/bin/sh

set -e

sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc

sudo apt-add-repository 'deb http://repos.codelite.org/wx3.1.2/ubuntu/ disco universe'

sudo apt-get update -y

