
# This files updates debian package files

DEBIAN_PROJECT_DIRECTORY=~/PCYNLITX.PROJECT/PACKAGE.BUILD.TOOLS/Debian_Packaging
DEBIAN_RELEASE=~/PCYNLITX.PROJECT.LIBRARY/PCYNLITX_RELEASE_PACKAGES/DEBIAN_RELEASE/pcynlitx_debian
DEBIAN_CONTROL_DIR=$DEBIAN_RELEASE/DEBIAN
DEBIAN_USER_DIR=$DEBIAN_RELEASE/usr
DEBIAN_USER_BIN=$DEBIAN_USER_DIR/bin
DEBIAN_USER_SHARE=$DEBIAN_USER_DIR/share
DEBIAN_USER_SHARE_DOC=$DEBIAN_USER_SHARE/doc
DEBIAN_USER_SHARE_PCYNLITX=$DEBIAN_USER_SHARE/Pcynlitx
DEBIAN_USER_SHARE_PCYNLITX_APP=$DEBIAN_USER_SHARE_PCYNLITX/applications
DEBIAN_USER_SHARE_PCYNLITX_ICONS=$DEBIAN_USER_SHARE_PCYNLITX/icons
GUI_DEVELOPMENT=~/PCYNLITX.PROJECT/GUI.DEVELOPMENT



cd $GUI_DEVELOPMENT

bash Update_Project_Binaries.sh > Compiler_Output

bash GUI_Compiler.sh > Compiler_Output


cd $DEBIAN_PROJECT_DIRECTORY/DEBIAN

cp control $DEBIAN_CONTROL_DIR

cp postinst $DEBIAN_CONTROL_DIR

cp postrm $DEBIAN_CONTROL_DIR

cp preinst $DEBIAN_CONTROL_DIR



cd $DEBIAN_PROJECT_DIRECTORY/usr/share/doc

cp Copyright $DEBIAN_USER_SHARE_DOC


cd $DEBIAN_PROJECT_DIRECTORY/usr/share/Pcynlitx/applications

cp pcynlitx.desktop $DEBIAN_USER_SHARE_PCYNLITX_APP



cd $DEBIAN_PROJECT_DIRECTORY/usr/share/Pcynlitx/icons

cp archive.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp build_executable.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp close_tab.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp close.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp empty_project_file.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp file_save.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp file.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp folder.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp help_documents.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp open_terminal.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp open_tree_view.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp pane_close_icon.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp pcynlitx.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp print_descriptions.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS

cp select_project_file.png $DEBIAN_USER_SHARE_PCYNLITX_ICONS


cd $DEBIAN_PROJECT_DIRECTORY/usr/share/Pcynlitx/

cp Intro_File.png $DEBIAN_USER_SHARE_PCYNLITX

cd $DEBIAN_USER_BIN

sudo chmod 0777 Description_Printer

sudo chmod 0777 Description_Recorder

sudo chmod 0777 Descriptor_File_Reader

sudo chmod 0777 Empty_Process_Descriptor_File_Builder

sudo chmod 0777 Pcynlitx_Kernel

sudo chmod 0777 MT_Project_Builder

sudo chmod 0777 Pcynlitx
